/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) ٢٠٢٦ STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_gpio_driver.h"
#include "stm32f103x6.h"

void  clock_init(){
	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_init(){

	//PA1 input highz floating   (reset state)
	GPIO_PinConfig_t PinCfg;
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA,&PinCfg);

	//PB1 (output push-pull mode)
	//01: Output mode, max speed 10MHZ
	//CNF 00: General perpose output push-pull
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB,&PinCfg);

	//PA13 input highz floating   (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA,&PinCfg);

	//PB13 (output push-pull mode)
	//01: Output mode, max speed 10MHZ
	//CNF 00: General perpose output push-pull
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB,&PinCfg);
}

void wait_ms(uint32_t time){
	uint32_t i ,j;
	for (i=0;i<time;i++)
		for (j=0;j<255;j++);
}

int main(void)
{

	clock_init();
	GPIO_init();

    while(1){
    	//PA1 >>>>Connected external PUR
    	if(MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN_1) == 0)//press
    	{
    		MCAL_GPIO_TogglePin(GPIOB,GPIO_PIN_1);
    		while (MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN_1) == 0); //Single Presssing
    	}
    	//PA13 >>>>Connected external PDR
    	if(MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN_13) == 0)//press
    	{
    		MCAL_GPIO_TogglePin(GPIOB,GPIO_PIN_13);
    	}
    	wait_ms(1);
    }
}
